### ISSUE TITLE
thaks

### ISSUE THREAD

**Issue by stepByStepToSky** [meetshah1995/tf-3dgan#1]
@meetshah1995  hello，I wonder have you get the answer of that paper ?  And please tell me how to run your code. thank you.

**Comment by meetps** [comment]
@stepByStepToSky  Please run the `3dgan_mit_biasfree.py` after setting the path appropriately in `dataIO.py`.  I've fixed minor issues here and there.

I'm planning to add instructions to the readme soon about downloading the data etc, meanwhile you can download the shapenet data from this link : http://3dshapenets.cs.princeton.edu/3DShapeNetsCode.zip
