### ISSUE TITLE
Issue in Training

### ISSUE THREAD

**Issue by NitinJSanket** [meetshah1995/tf-3dgan#16]
Hi Meet,
Thanks for your awesome code. Appreciate all your hardwork. I'm having trouble in training. 
Here are the instructions I followed:
Installed all required dependencies. (I have Tensorflow 1.0.0)./
In dataIO.py:
I modified the LOCAL_PATH to volumetrix_data path in the 3DShapeNets folder.
I did not understand what SERVER_PATH means. 
In 3dgan_mit_biasfree.py I tried making is_local=True but no difference.

I run my code using the following command from the src folder
python 3dgan_mit_biasfree.py 0 /media/nitin/Research/Thesis/
Where the directory /media/nitin/Research/Thesis/ is an empty folder (Do I need anything here?)

I get the following error:
 Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files 

Your help would be highly appreciated.

Thanks,
Nitin

**Comment by meetps** [comment]
@NitinJSanket Can you post the entire trace here? It's a little difficult to say where exactly the problem is.

Also can you try this: `python 3dgan_mit_biasfree.py 0 0`

**Comment by NitinJSanket** [comment]
@meetshah1995  Thanks for the help! The command you recommended works like a charm! BTW out of curiosity what does the last argument being 0 do? Sorry for being lazy to read your code and find out :)

**Comment by ghost** [comment]
@NitinJSanket  the last argument being 0 sets `checkpoint=None` which means there is no model ckpt path provided.
```
 if __name__ == '__main__':
    test = bool(int(sys.argv[1]))
    if test:
        path = sys.argv[2]
        testGAN(trained_model_path=path)
    else:
        ckpt = sys.argv[2]
        if ckpt == '0':
            trainGAN(is_dummy=False, checkpoint=None)
        else:
            trainGAN(is_dummy=False, checkpoint=ckpt)
```

**Comment by NitinJSanket** [comment]
@MangoChao  Thanks :)

**Comment by MangoChao** [comment]
@meetshah1995 thanks for your great work. i'm working on  generating 3d models using GAN, inheriting your code. and there are some questions which confuses me a lot.
do you reproduce the results? i got terrible results running `3dgan_mit_biasfree.py` to generate chairs.

thanks very much for your help!
