### ISSUE TITLE
Not able to generate chairs from Trained Model

### ISSUE THREAD

**Issue by NitinJSanket** [meetshah1995/tf-3dgan#17]
Hi Meet,
I successfully trained the model for 20000 epochs without any error. But why I try to generate chairs like your readme suggests using the following command 
`python 3dgan_mit_biasfree.py 1 ./models/biasfree_19960.cptk`

Nothing happens. The code opens cuda but does nothing 

This is my trace

`I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
All dependencies not loaded, some functionality may not work
Tensor("gen/Relu:0", shape=(32, 4, 4, 4, 512), dtype=float32) g1
Tensor("gen/Relu_1:0", shape=(32, 8, 8, 8, 256), dtype=float32) g2
Tensor("gen/Relu_2:0", shape=(32, 16, 16, 16, 128), dtype=float32) g3
Tensor("gen/Relu_3:0", shape=(32, 32, 32, 32, 64), dtype=float32) g4
Tensor("gen/Tanh:0", shape=(32, 64, 64, 64, 1), dtype=float32) g5
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:01:00.0
Total memory: 11.90GiB
Free memory: 11.01GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:01:00.0)
`

Please do let me know if I am missing something.

Thanks,
Nitin

**Comment by meetps** [comment]
You need to input the threshold here: 

https://github.com/meetshah1995/tf-3dgan/blob/master/src/3dgan_mit_biasfree.py#L251
