### ISSUE TITLE
Recommended VRAM size?

### ISSUE THREAD

**Issue by Gnailimixam** [meetshah1995/tf-3dgan#5]
Hi,
I'm an industrial-design student and quite new to tensorflow and machine-learning. 
I'm gonna build up a new machine and therefor looking for a good but cheap graphic card.

Could you tell me what VRAM size you would recommend for running your fascinating code?

Thanks!

**Comment by meetps** [comment]
I trained it on a Titan X (12 GB VRAM). You could go ahead with 1080 Ti which is pretty cheap. Any GPU with VRAM around 4GB would be enough for you to run this code.

Please use github issues only for problems/concerns in the code.
