### ISSUE TITLE
How to use generator-mode? DataLossError

### ISSUE THREAD

**Issue by Gnailimixam** [meetshah1995/tf-3dgan#8]
For a quick test I've just trained your 3dgan with: 
$ python 3dgan_mit_biasfree.py 0 0 

and changed in code:

n_epochs=248
batch_size=16

After that I got new folders 'models' and 'train_sample'.
In 'models' I have some 'biasfree_XY.cptk.*' etc and one 'checkpoint' .
In 'train_sample' just two 'biasfree_0' and 'biasfree_200'.

When I'm trying to generate chairs with
  $ python 3dgan_mit_biasfree.py  1 ./models 
or
  $ python 3dgan_mit_biasfree.py  1 ./train_sample

an long error occurs with at the end:

"DataLossError: (see above for traceback): unable to open table file ./models [or ./train_sample]: Failed precondition: models: perhaps your file is in a different file format and you need to use a different restore operator? [...]"

What am I doing wrong?

Thanks for your patience!

**Comment by meetps** [comment]
Please provide entire path to the generated checkpoint file : 

`python 3dgan_mit_biasfree.py 1 ./models/some_file_name.cptk`

**Comment by Gnailimixam** [comment]
Thanks for your fast answer!
No error occures now.

But now the code stops doing anything after line

`I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0`

VRAM is stil in usage put not working (temp: 33C).

I'm waiting no for a few hours but nothing has changed yet.

What could be the problem?

**Comment by meetps** [comment]
You need to enter the sigma value for the gaussian to draw random noise from which will be used in the generator z variable. 

Pls refer line : https://github.com/meetshah1995/tf-3dgan/blob/master/src/3dgan_mit_biasfree.py#L251

**Comment by anandbhattad** [comment]
@meetshah1995  can you explain what your code here is doing in test time  `print g_objects[id_ch[i]].max(), g_objects[id_ch[i]].min(), g_objects[id_ch[i]].shape` What is max and min here? Thanks!

**Comment by meetps** [comment]
It's a harmless print statement to see the maximum and minimum activation values in the generated voxels and it's shape.

**Comment by anandbhattad** [comment]
Thanks for quick reply. I am using visdom for first time. It executes properly, but I don't see any generated chair images. I am using `python -m visdom.server` and I get `It's Alive!` as output and my visdom screen is just blue and cannot see any images here. Anything that I am doing wrong here? Also, can we store these generated results in .mat format? Thanks again!

**Comment by meetps** [comment]
Are you sure you are inputting the variance at each step? 

https://github.com/meetshah1995/tf-3dgan/blob/master/src/3dgan_mit_biasfree.py#L251

To save voxels to mat, the `scipy.matio` function might be handy.

**Comment by anandbhattad** [comment]
Yes, I replaced `next_sigma = float(raw_input())` to `next_sigma = 0.44`. It runs without any error too and gives me results like below: 
`1.0 -1.0 (64, 64, 64, 1) \\
0.999999 -1.0 (64, 64, 64, 1) \\
1.0 -1.0 (64, 64, 64, 1) \\
1.0 -1.0 (64, 64, 64, 1) \\
1.0 -1.0 (64, 64, 64, 1)`

I also tried inputting the variance at each step. Still no success!
Thank you again for your time.

**Comment by ghost** [comment]
@bhattad2 maybe it's a Visdom issue. do u get any buttons on the Visdom screen, like Clear, Save or Filter?

**Comment by anandbhattad** [comment]
@MangoChao Thanks a lot for your comment. I was able to solve this issue.

**Comment by iniludi** [comment]
@anandbhattad hi, I have the same issue with Visdom. How did you solve this issue?
