### ISSUE TITLE
Training Problem

### ISSUE THREAD

**Issue by Willyshuai** [meetshah1995/tf-3dgan#9]
I can't wait to try this implementation . However, when I want to train the model and type the following words:
python 3dgan_mit_biasfree.py 0 0

The error would show:
  File "/home/willy/Downloads/tf-3dgan-master/src/dataIO.py", line 51, in getVFByMarchingCubes
    v, f =  sk.marching_cubes_lewiner(voxels, level=threshold)
ValueError: too many values to unpack 

Any ideas ?

**Comment by meetps** [comment]
I verified the training process. It works just fine. Besides there is no such line as :  `v, f = sk.marching_cubes_lewiner(voxels, level=threshold)` in the script.

Please paste the entire trace here for me to be able to debug.

**Comment by Willyshuai** [comment]
Hi , here are some steps I took,
1. Download the training data from the 3D Shapenet
2. Extract the zip and modify the path appropriately in dataIO.py (I modified the following to paths )
LOCAL_PATH = '/home/willy/Downloads/3DShapeNets/volumetric_data/'
SERVER_PATH = '/home/willy/Downloads/3DShapeNets/volumetric_data/'
3. I ran the following words: python 3dgan_mit_biasfree.py 0 0

The error would show below:
Traceback (most recent call last):
  File "3dgan_mit_biasfree.py", line 268, in <module>
    trainGAN(is_dummy=False, checkpoint=None)
  File "3dgan_mit_biasfree.py", line 226, in trainGAN
    d.plotVoxelVisdom(np.squeeze(g_objects[id_ch[i]]>0.5), vis, '_'.join(map(str,[epoch,i])))          
  File "/home/willy/Downloads/tf-3dgan-master/src/dataIO.py", line 59, in plotVoxelVisdom
    v, f = getVFByMarchingCubes(voxels)
  File "/home/willy/Downloads/tf-3dgan-master/src/dataIO.py", line 51, in getVFByMarchingCubes
    v, f =  sk.marching_cubes(voxels, level=threshold)
ValueError: too many values to unpack

Here are my requirements:
system: ubuntu 14.04 LTS
memory:31.4 GiB
Processor:Intel® Core™ i7 CPU 860 @ 2.80GHz × 8 
Graphics:GeForce GTX 1080 Ti/PCIe/SSE2
OS type:64-bit
Disk: 950 GB
python:2.7
tensorflow:1.0.0
pip install scipy scikit-image stl visdom<One-line installation>

Still can't figure out the reason...

**Comment by Willyshuai** [comment]
Well , it seems like I've fixed that problem because of the scikit-image version. However, I encountered the error when training the model (visdom will show generated chairs after every 200 minibatches) as follows:
`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/visdom/__init__.py", line 228, in _send
    data=json.dumps(msg),
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by <class 'socket.error'>: [Errno 111] Connection refused)
Exception in user code:`

Sorry I just new to it....

**Comment by meetps** [comment]
Do you have visdom server running?

You need to run visdom server in the background to be able to visualize the results.

Just run `python -m visdom.server` in a separate terminal. I'll add this to the README, thanks.

Have a look at the updated README
